{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
{{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{- with .Values.deployment.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
{{- with .Values.replicaCount }}
  replicas: {{ . }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
      release: {{ .Release.Name }}
{{- if .Values.deployment.labels }}
      type: {{ .Values.deployment.labels.type | default (include "common.name" .)  }}
{{- end }}      
{{- with .Values.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  minReadySeconds: {{ default 0 (.Values.deployment.minReadySeconds | int) }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- if .Values.deployment.pod}}
{{- with .Values.deployment.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
      labels:
        app: {{ include "common.name" . }}
        release: {{ .Release.Name | quote }}
        serve: "true"
{{- if .Values.deployment.labels }}
        type: {{ .Values.deployment.labels.type | default (include "common.name" .)  }}
{{- end }}         
{{- if .Values.deployment.pod}}
{{- with .Values.deployment.pod.labels }}
{{ toYaml .| indent 8 }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.deployment.topologySpreadConstraints }}
{{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints: 
{{ toYaml . | indent 8 }}      
{{- end }}            
{{- end }}    
{{- if index .Values "serviceAccountName" }}
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- end }}
      terminationGracePeriodSeconds: {{ default 30 (.Values.deployment.terminationGracePeriodSeconds | int) }}
      dnsPolicy: {{ default "ClusterFirst" .Values.deployment.dnsPolicy }}
{{- with .Values.deployment.dnsConfig }}
      dnsConfig:
{{ toYaml . | indent 10 }}
{{- end }}
{{- if .Values.deployment.affinity }}
      affinity:
{{- if or .Values.deployment.affinity.podAntiAffinity (eq .Values.deployment.affinity.affinityRule "ShouldBeOnDifferentNode") }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
{{- if .Values.deployment.affinity.podAntiAffinity }}
{{- if .Values.deployment.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
{{- with .Values.deployment.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.deployment.affinity.affinityRule "ShouldBeOnDifferentNode" }}
{{- include "monochart.affinityRule.ShouldBeOnDifferentNode" . | nindent 10 }}
{{- end }}
{{- end }}
{{- if .Values.deployment.affinity.podAffinity }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
{{- with .Values.deployment.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution }}
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
{{- if .Values.deployment.affinity.nodeAffinity }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
{{- if .Values.deployment.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
{{- with .Values.deployment.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
{{ toYaml . | indent 16 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.deployment.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ required "image.repository is required!" .Values.image.repository }}:{{ required "image.tag is required!" .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ include "monochart.env" . | indent 8 }}
{{- with .Values.deployment.pod.command }}
        command:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.deployment.pod.args }}
        args:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.deployment.pod.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.deployment.pod.lifecycle }}
        lifecycle:
{{ toYaml . | indent 10 }}
{{- end }}
        ports:
{{- $registeredPorts := list -}}
{{- range $serviceName, $service := .Values.service }}
{{- $portId := (sha256sum (toString $service)) -}}
{{- if $service.enabled }}
{{- range $name, $port := (get $service "ports") }}
{{- if (and $port (not (has $portId $registeredPorts))) }}
          - name: {{ $name }}
            containerPort: {{ $port.internal }}
            protocol: {{ default "TCP" $port.protocol  }}
{{- $registeredPorts = append $registeredPorts $portId -}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - mountPath: {{ .Values.persistence.mountPath | quote }}
          name: storage
        {{- end }}
        {{- include "monochart.files.volumeMounts" . |  nindent 8 }}
{{- with .Values.probes }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.deployment.pod.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
{{- end }}
      imagePullSecrets:
{{- with .Values.image.pullSecrets }}
      {{- range . }}
        - name: {{ . }}
      {{- end }}
{{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: storage
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "common.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- end }}
      {{- include "monochart.files.volumes" . | nindent 6 }}
{{- end -}}
