{{- $root := . -}}
{{- $serviceName := include "common.fullname" . -}}
{{- range $name, $service := .Values.service -}}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $name "default" }}
  name: {{ $serviceName }}
  {{- else }}
  name: {{ $serviceName }}-{{ $name }}
  {{- end }}
{{- with $service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" $root | indent 4 }}
{{- with $service.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  type: {{ $service.type }}
{{- if eq $service.type "ExternalName" }}
  externalName: {{ $service.externalName }}
{{- else }}
  ports:
{{- range $name, $port := $service.ports }}
{{- if $port }}
  - targetPort: {{ $name }}
    port: {{ $port.external }}
    protocol: {{ default "TCP" $port.protocol  }}
    name: {{ $name }}
{{- end }}
{{- end }}
{{- if $service.selector }}
{{- with $service.selector }}
  selector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- else }}
  selector:
    app: {{ include "common.name" $root }}
    release: {{ $root.Release.Name }}
    serve: "true"
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
