{{- if .Values.storageclass -}}
{{- if .Values.storageclass.enabled -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{- with .Values.storageclass.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
provisioner: {{ .Values.storageclass.provisioner }}
{{- if .Values.storageclass.parameters }}
parameters:
  pool: {{ .Values.storageclass.pool }}
  description: Kubernetes volume
  fsType: {{ .Values.storageclass.fsType }}
{{- end }}

{{- end -}}
{{- end -}}