apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "burrow.fullname" . }}
  labels:
{{ include "burrow.labels" . | indent 4 }}
  {{- with .Values.burrow.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "burrow.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/burrow-configmap.yaml") . | sha256sum }}
        checksum/templates: {{ include (print $.Template.BasePath "/burrow-templates-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "burrow.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ['sleep', '36000']
          {{- if .Values.burrow.secretConfig }}
          envFrom:
          - secretRef:
              name: {{ .Values.burrow.secretConfig }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/burrow
              name: config
            - mountPath: {{ .Values.burrow.templateDir }}
              name: templates
          ports:
            - name: http
              containerPort: {{ last (splitList ":" .Values.burrow.config.httpserver.default.address) }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /burrow/admin
              port: http
          readinessProbe:
            httpGet:
              path: /burrow/admin
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "burrow.fullname" . }}
        - name: templates
          configMap:
            name: {{ template "burrow.fullname" . }}-templates
