{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{include "kminion.fullname" .}}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kminion.labels" . | nindent 4}}
    {{- if .Values.serviceMonitor.additionalLabels}}
    {{toYaml .Values.serviceMonitor.additionalLabels | nindent 4}}
    {{- end}}
spec:
  selector:
    matchLabels:
      {{- include "kminion.labels" . | nindent 6}}
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
      {{ toYaml .Values.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
  {{- if .Values.serviceMonitor.targetLabels}}
  targetLabels:
    {{- toYaml .Values.serviceMonitor.targetLabels | nindent 4}}
  {{- end}}
  {{- if .Values.customLabels }}
  podTargetLabels:
    {{- (keys .Values.customLabels | sortAlpha) | toYaml | nindent 4 }}
  {{- end}}
 {{- end }}
